### PR TITLE
WIP: Generate and deploy to Netlify in CI

### PR DESCRIPTION
**Pull request by srid**
[Includes #8]

Just playing with it in the interest of https://github.com/srid/rib/issues/93

Not ready to be merged yet.

### CODE REVIEW

**Comment by srid** [comment]
Seems to have done _something_ though I'm not sure _where_ exactly it deployed it, if at all ...
image

**Comment by srid** [comment]
Okay, now it says "Deploying" - but nothing comes after:

image

**Comment by srid** [comment]
@JonathanReeve Any idea about this "Mixed content" error from Netlify? https://github.com/open-editions/open-editions.org/runs/403388638

**Comment by srid** [comment]
Okay, the cli action seems to work. Though it requires credentials set on this repo I guess:

image

**Comment by JonathanReeve** [comment]
Awesome. Do I just add auth environment variables via Settings -> Secrets, for this repo?

**Comment by JonathanReeve** [comment]
I added secrets, so I think I should be able to try merging this once it's not a draft.

**Comment by srid** [comment]
I'm using [this blog post](https://sung.codes/blog/2019/12/25/building-gatsby-with-git-hub-actions-and-deploying-to-netlify/) as a reference, which does talk about adding secret keys to the repo.

I pushed a new commit to trigger the build, but the deploy step seems to be stuck ...  hmm ....

**Comment by JonathanReeve** [comment]
It looks like it's just missing the auth details? Now that I added them, it should work, I imagine. I just triggered a rebuild just now, so we'll see.

**Comment by srid** [comment]
It tries to open the web browser and fails:

```
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=f7d8632091e84532a739eb0af35df741
---------------------------
Error: Unable to open browser automatically

Please open your browser & open the URL below to login:
https://app.netlify.com/authorize?response_type=ticket&ticket=f7d8632091e84532a739eb0af35df741
---------------------------
TimeoutError: Promise timed out after 3600000 milliseconds
    at Timeout.setTimeout [as _onTimeout] (/usr/local/share/.config/yarn/global/node_modules/p-timeout/index.js:27:54)
```

I think there is something we are not doing right. I have other things to do right now, so my efforts on https://github.com/srid/rib/issues/93 may have to wait a bit.

**Comment by JonathanReeve** [comment]
I got this to work, kind of, through [a kind of dirty hack](https://github.com/open-editions/open-editions.org/blob/master/.github/workflows/main.yml) where I compile to the gh-pages branch, and then get Netlify to serve that branch. It works OK for now, so I'll close this PR, but if you have any ideas about how to streamline this action, or speed it up, please let me know. What would be really nice is to do something like `-uses: srid/compile-with-rib-action` that wraps up all these steps.

**Pull request closed without merging**
