### PR TITLE
Update rib to use Rib.Route

### PR DESCRIPTION
**Pull request by srid**
The new Route type is much cleaner in the upcoming rib 0.7

https://github.com/srid/rib/pull/110

### CODE REVIEW

**Comment by JonathanReeve** [comment]
This is awesome, thanks for this!

Although I can't get this branch to build: `nix-shell` fails because pandoc-include-code 1.5.0 apparently needs pandoc-types==1.20 so the build fails with: 

```
Setup: Encountered missing dependencies:
pandoc-types ==1.20
```

My nix-fu isn't strong enough to debug this. Do you know how to fix it?

**Comment by srid** [comment]
@JonathanReeve `nix-shell` works fine for me. You can also see that `nix-build` builds in the CI. 

Is there something unique about your environment? Can you show me what happens when you run `env | grep NIX_; nix-shell`, maybe as an [asciinema](https://asciinema.org/)? 

You can also try `nix-shell --pure`.

**Comment by JonathanReeve** [comment]
Oh weird, I just realized it's because I had [an uncommitted shell.nix so that I could develop this with additional haskell packages](https://github.com/open-editions/open-editions.org/blob/master/shell.nix). 

Any ideas about how to fix that file so that it gets the latest version of Rib? I'm awful at Nix.

**Comment by srid** [comment]
If the additional Haskell package already exists in nixpkgs, it should be listed in the cabal file; see [this comment](https://github.com/open-editions/open-editions.org/commit/8985b6dd328ed01df8bc7a4db00ab64965ce0606#commitcomment-36885093).

If not, you would pass the exact git revision to `source-overrides` ([example](https://github.com/srid/website/blob/2cce21/default.nix#L19-L28)).

**Comment by srid** [comment]
So, 
1. Add the packages to your cabal file
2.  `rm shell.nix` (you don't really need this; adding this file will make `nix-shell` use that *instead of* `default.nix`)

**Comment by JonathanReeve** [comment]
Nevermind, I'm seeing now that I add new packages via the .cabal file. I managed to test this and everything looks great! Merging. Thanks again!

**Pull request merged**
